### ISSUE TITLE
Assessment Results

### ISSUE THREAD

**Issue by rwarbelow** [N-Gibson/mod_0_skills#1]
# Checklist/Rubric

### Part I: Creating Directories and Files; Initializing Git and Pushing to GitHub

- [x] I named my directories correctly. 
- [x] I named my files correctly.
- [x] I structured my files and directories correctly. 
- [x] I made one initial commit.
- [x] I pushed my initial commit to GitHub.

### Part II: Top Down Design

- [x] I broke down larger processes into smaller layers.
- [x] I added and committed my changes with a properly formatted commit message starting with a verb and a capital letter.
- [x] I pushed my changes to Github. 

### Part III: Classes, Objects, Attributes, and Methods

Class #1 Checklist
- [x] I structured and named my directories and files correctly.
- [x] The three attributes I chose for **Class #1** represent properties or characteristics.
- [x] I identified the data type (string, integer, boolean, array, hash/object, datetime) for attributes in **Class 1**.
- [ ] The three methods I chose for **Class #1** represent behaviors or actions.
> It looks like your methods are questions instead of behaviors/actions. Although methods can occasionally be questions, we're looking for things that the class can *do* or *have done to it*. For example, here might be some good methods for your table class:
> `add_seats` (modifies the seats attribute)), `seat_guests` (changes the table occupation attribute), `clean` (changes a hypothetical cleanliness attribute), `reserve` (adds a person's name to a hypothetical reservations array attribute), etc. 
>
> This next piece of feedback is beyond the scope of what we covered in Mod 0, but it will help you when you start to write code: Make sure that your methods only do *one* thing. For example, `is_table_occupied` should return true/false, but it should not also modify the table occupation attribute. That would be better separated into a different method, maybe `occupy_table`. 
- [x] I described what the methods do in **Class 1**.
- [x] I added and committed the `class_1.txt` file **separately** with a properly formatted commit message. 

Class #1 Example Object Checklist
- [x] The object I chose for **Class 1** is an instance of this class. 
- [x] I listed the values for each attribute of this object. 
- [ ] I listed the results of each method for this object. 
> It looks like the methods for the example object are different from the ones in the class template. 
- [x] I added and committed the `class_1_example_object.txt` file **separately** with a properly formatted commit message. 

Class #2 Checklist
- [x] The three attributes I chose for **Class #2** represent states or characteristics.
- [ ] I identified the data type (string, integer, boolean, array, hash/object, datetime) for attributes in **Class 2**.
> For `Types of Ingredients` attribute, you probably want to use an array instead of a string. A string would imply one ingredient, while an array would imply many (like ["potato", "cheese", "garlic"], etc)
- [ ] The three methods I chose for **Class #2** represent behaviors or actions.
> (See note about methods from first class)
- [x] I described what the methods do in **Class 2**.
- [x] I added and committed the `class_2.txt` file **separately** with a properly formatted commit message. 

Class #2 Example Object Checklist
- [x] The object I chose for **Class 2** is an instance of this class. 
- [x] I listed the values for each attribute of this object. 
- [ ] I listed the results of each method for this object. 
> Hmm... I'm a little confused by the methods on the Chicken Parm object since they don't match up with the methods you defined for the class in your `class_2.txt` file. Think of methods as things that the specific object should be responsible for. In this case, `How many dishes included the wrong number of ingredients?` shouldn't be something that the Chicken Parm is calculating. If you had a class `Restaurant`, then that might be a good question for that object, but one specific dish shouldn't know anything about all of the dishes being made. 
> Good examples of methods for this object might be `add_ingredient`, `eat`, `heat`, etc. 
- [x] I added and committed the `class_2_example_object.txt` file **separately** with a properly formatted commit message. 

### Assessment Results
- [ ] Technical Ready
- [x] Pending
> Next steps:
> Using the feedback above, create one more file called class_3.txt and define a class that you would find in a city. Be sure that the methods are all actions of/for that specific class. Create another file called class_3_example_object.txt and give the attributes and methods for a specific object of that class.
- [ ] Not Technical Ready
